version: "2"
services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    privileged: true
    user: root
    # restart: always
    ports:
      - 8080:8080 
      - 50000:50000
    volumes:
     - jenkins_data:/var/jenkins_home
     - ./tmp:/var/run/docker.sock
volumes:
  jenkins_data: