---
- hosts: all
  become: yes
  vars:
    packages:
      - docker*
      - python3
      - pip
      - boto3
      - docker-py
      - docker-compose
  tasks:
    - name: docker-compose down
      shell:
        cmd: |
              /usr/local/bin/docker-compose down -d       
      args:
        chdir: /usr/tmp/mysql
      register: output
    - debug:
        msg: '{{ output }}'

    - name: Remove packages
      yum:
        name: " {{ item }}"
        state: absent
      with_items: "{{ packages }}"

    - name: remove aws folder
      file:
        path: /home/{{ ansible_user}}/.aws
        state: absent
      register: output
    - debug:
        msg: '{{ output }}'